version: '3.9'

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    expose:
      - 5678
    restart: always
    networks:
      - net1

  nginx:
    build:
        context: ./docker/prod/nginx
        dockerfile: Dockerfile
    volumes:
      - type: volume
        source: static_volume
        target: /home/app/static/
        volume:
          nocopy: false
      - ./nginx/ssl:/etc/ssl
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
    ports:
      - 80:80
      - 443:433

    # depends_on:
    #   - backend
    networks:
      - net1

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - net1


volumes:
  static_volume:
    
networks:
  net1: