server {

    listen 80;
    listen [::]:80;

    server_name fenixcorp.gt www.fenixcorp.gt;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
      return 301 https://data.fenixcorp.gt:8002;
    }

}