upstream n8n {
    server n8n:5678;
}

# HTTP - redirect all requests to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name krakenlabs.site www.krakenlabs.site;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://$host$request_uri;  # Use $host instead of hardcoding the domain
    }
}

# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name krakenlabs.site;

    ssl_certificate /etc/nginx/ssl/live/krakenlabs.site/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/krakenlabs.site/privkey.pem;

    large_client_header_buffers 16 20480k;
    client_max_body_size 20M;
    
    location / {
        proxy_pass http://n8n;
        proxy_buffers 4 32k;
        proxy_buffer_size 32k;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Host $server_name;
        
        proxy_connect_timeout 3600;
        proxy_send_timeout 3600;
        proxy_read_timeout 3600;
        send_timeout 3600;
    }
}